
# 3.2.3 Уход от циклов: обработка данных с применением массивов

## Задание 1

**Условие:**
Создайте случайный целочисленный массив ```ndarray``` из ```12``` элементов, принадлежащих отрезку ```[0,10]```. Сделайте две матрицы размера ```(3,4)``` с порядком следования элементов в стиле С и Fortran. Найдите поэлементное произведение этих матриц, а после - максимальный элемент в полученной матрице. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```25```)



**Решение:**

In [ ]:
import numpy as np

# Установим seed для воспроизводимости результатов
np.random.seed(1000)

# Создаем случайный целочисленный массив из 12 элементов, принадлежащих отрезку [0,10]
arr = np.random.randint(0, 11, 12)

# Создаем матрицу размера (3,4) в стиле C
matrix_c = arr.reshape((3, 4), order='C')

# Создаем матрицу размера (3,4) в стиле Fortran
matrix_f = arr.reshape((3, 4), order='F')

# Находим поэлементное произведение матриц
elementwise_product = matrix_c * matrix_f

# Находим максимальный элемент в полученной матрице
max_element = np.max(elementwise_product)

print("Матрица в стиле C:")
print(matrix_c)
print("\nМатрица в стиле Fortran:")
print(matrix_f)
print("\nПоэлементное произведение:")
print(elementwise_product)
print("\nМаксимальный элемент в полученной матрице:", max_element)

Матрица в стиле C:
[[ 3  7  7  0]
 [ 1  0  9  8]
 [ 9  4 10 10]]

Матрица в стиле Fortran:
[[ 3  0  9  4]
 [ 7  1  8 10]
 [ 7  0  9 10]]

Поэлементное произведение:
[[  9   0  63   0]
 [  7   0  72  80]
 [ 63   0  90 100]]

Максимальный элемент в полученной матрице: 100


## Задание 2

**Условие:**
Создайте ```3``` случайных целочисленных массива ```ndarray``` размера ```(10,10)``` элементов, принадлежащих отрезку ```[0,10]```. Сделайте из данных массивов один трехмерный массив. Найдя размер полученного массива, вычислите количество элементов в нем. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```56```)


**Решение:**

In [ ]:
import numpy as np

# Установим seed для воспроизводимости результатов
np.random.seed(1000)

# Создаем 3 случайных целочисленных массива размером (10,10) элементов, принадлежащих отрезку [0,10]
array1 = np.random.randint(0, 11, size=(10, 10))
array2 = np.random.randint(0, 11, size=(10, 10))
array3 = np.random.randint(0, 11, size=(10, 10))

# Создаем трехмерный массив из данных массивов
three_dim_array = np.array([array1, array2, array3])

# Найдем размер полученного массива
shape = three_dim_array.shape

# Вычисляем количество элементов в трехмерном массиве
num_elements = np.prod(shape)

print("Размер полученного трехмерного массива:", shape)
print("Количество элементов в трехмерном массиве:", num_elements)

Размер полученного трехмерного массива: (3, 10, 10)
Количество элементов в трехмерном массиве: 300


## Задание 3

**Условие:**
С использование методов ```ndarray``` сформируйте массив размера ```(20,2)```, в первом столбце которого идут целые числа, начиная с ```1```,а во втором - первые 20 нечетных чисел, начиная с ```3```. Найдите среднее значение второго столбца.

**Формат ответа:**
Число (например, ```34```)



**Решение:**

In [ ]:
import numpy as np

# Создаем массив размера (20, 2), где первый столбец содержит целые числа, начиная с 1,
# а второй столбец содержит первые 20 нечетных чисел, начиная с 3.
array = np.zeros((20, 2), dtype=int)
array[:, 0] = np.arange(1, 21)  # Заполняем первый столбец числами от 1 до 20
array[:, 1] = np.arange(3, 3 + 2 * 20, 2)  # Заполняем второй столбец первыми 20 нечетными числами, начиная с 3

# Найдем среднее значение второго столбца
mean_second_column = np.mean(array[:, 1])

print("Массив:")
print(array)
print("\nСреднее значение второго столбца:", mean_second_column)

Массив:
[[ 1  3]
 [ 2  5]
 [ 3  7]
 [ 4  9]
 [ 5 11]
 [ 6 13]
 [ 7 15]
 [ 8 17]
 [ 9 19]
 [10 21]
 [11 23]
 [12 25]
 [13 27]
 [14 29]
 [15 31]
 [16 33]
 [17 35]
 [18 37]
 [19 39]
 [20 41]]

Среднее значение второго столбца: 22.0
